---
name: Dependency Review

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  dependency-review:
    name: Dependency Review
    permissions:
      contents: read
      pull-requests: write
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/dependency-review.yml@7254f4a35b6251bf442bf84335b6bd27f9d88689 # v4.1.4
